package modelo;
// Generated 08-jul-2014 20:17:42 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private Puesto puesto;
     private Departamento departamento;
     private String nombre;
     private double salario;
     private Date fechaAlta;
     private Set empleadoProyectos = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(Puesto puesto, String nombre, double salario) {
        this.puesto = puesto;
        this.nombre = nombre;
        this.salario = salario;
    }
    public Empleado(Puesto puesto, Departamento departamento, String nombre, double salario, Date fechaAlta, Set empleadoProyectos) {
       this.puesto = puesto;
       this.departamento = departamento;
       this.nombre = nombre;
       this.salario = salario;
       this.fechaAlta = fechaAlta;
       this.empleadoProyectos = empleadoProyectos;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Puesto getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Set getEmpleadoProyectos() {
        return this.empleadoProyectos;
    }
    
    public void setEmpleadoProyectos(Set empleadoProyectos) {
        this.empleadoProyectos = empleadoProyectos;
    }




}


