package modelo;
// Generated 10-jul-2014 19:43:41 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Idioma generated by hbm2java
 */
public class Idioma  implements java.io.Serializable {


     private Integer idIdioma;
     private String nombre;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Idioma() {
    }

	
    public Idioma(String nombre) {
        this.nombre = nombre;
    }
    public Idioma(String nombre, Set<Empleado> empleados) {
       this.nombre = nombre;
       this.empleados = empleados;
    }
   
    public Integer getIdIdioma() {
        return this.idIdioma;
    }
    
    public void setIdIdioma(Integer idIdioma) {
        this.idIdioma = idIdioma;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


