package modelo;
// Generated 10-jul-2014 19:43:41 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private Integer idProyecto;
     private String nombre;
     private String descripcion;
     private Set<EmpleadoProyecto> empleadoProyectos = new HashSet<EmpleadoProyecto>(0);

    public Proyecto() {
    }

	
    public Proyecto(String nombre) {
        this.nombre = nombre;
    }
    public Proyecto(String nombre, String descripcion, Set<EmpleadoProyecto> empleadoProyectos) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.empleadoProyectos = empleadoProyectos;
    }
   
    public Integer getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(Integer idProyecto) {
        this.idProyecto = idProyecto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<EmpleadoProyecto> getEmpleadoProyectos() {
        return this.empleadoProyectos;
    }
    
    public void setEmpleadoProyectos(Set<EmpleadoProyecto> empleadoProyectos) {
        this.empleadoProyectos = empleadoProyectos;
    }




}


